version: '3.8'

services:
  db:
    container_name: belgrade_db_hm
    volumes:
      - db_data_hm:/var/lib/postgresql/data

  scraper:
    container_name: belgrade_scraper_hm

  web:
    container_name: belgrade_web_hm

volumes:
  db_data_hm:
